In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))

In [3]:
x2=np.random.randint(low=1,high=20,size=(50,))

In [4]:
y=3+2*x1-4*x2+np.random.random((50,))

In [5]:
y

array([-22.84601678, -46.39021565, -24.20473164, -32.06606141,
       -60.20033191,  15.58417096, -16.7845182 , -32.77215543,
       -40.69094347, -12.96733857, -54.20783918,   5.62631538,
       -46.1946015 ,  19.98752854, -34.05855952,  11.19675219,
       -50.43306478, -32.3595807 , -12.88251202,  13.34219719,
       -50.4947351 , -40.67833002, -34.86774592, -14.45554546,
        13.75091202, -28.51512322, -16.56877419, -10.2857354 ,
        11.59335644, -10.65133354, -68.34455837,   7.88646466,
       -12.19768657, -34.15329048, -30.02336356, -44.86549814,
       -18.57139171, -50.61820694,  -6.36515151, -50.75334171,
       -42.18913912, -66.13359124, -64.64683386, -16.51904774,
       -68.26285008, -38.09181226, -30.20767515, -42.71408874,
        -2.60070281, -36.52086639])

In [6]:
x1

array([ 5,  5, 12,  8,  4, 14,  4,  4, 12, 14,  7, 15,  9, 14, 17,  8, 11,
       14, 14, 19,  1,  6,  9, 11, 19,  6,  4,  3, 14, 17,  2, 10,  8,  9,
       15,  4,  5,  9, 17,  3,  1,  3,  4, 12,  2,  7,  3, 15, 19, 16])

In [7]:
x2

array([ 9, 15, 13, 13, 18,  4,  7, 11, 17, 11, 18,  7, 17,  3, 18,  2, 19,
       16, 11,  7, 14, 14, 14, 10,  7, 11,  7,  5,  5, 12, 19,  4,  8, 14,
       16, 14,  8, 18, 11, 15, 12, 19, 19, 11, 19, 14, 10, 19, 11, 18])

In [8]:
x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})



In [9]:
x

intercept  x1  x2
0           1   5   9
1           1   5  15
2           1  12  13
3           1   8  13
4           1   4  18
5           1  14   4
6           1   4   7
7           1   4  11
8           1  12  17
9           1  14  11
10          1   7  18
11          1  15   7
12          1   9  17
13          1  14   3
14          1  17  18
15          1   8   2
16          1  11  19
17          1  14  16
18          1  14  11
19          1  19   7
20          1   1  14
21          1   6  14
22          1   9  14
23          1  11  10
24          1  19   7
25          1   6  11
26          1   4   7
27          1   3   5
28          1  14   5
29          1  17  12
30          1   2  19
31          1  10   4
32          1   8   8
33          1   9  14
34          1  15  16
35          1   4  14
36          1   5   8
37          1   9  18
38          1  17  11
39          1   3  15
40          1   1  12
41          1   3  19
42          1   4  19
43          1  12  11
44          1   2  19
45          1   7  14
46          1   3  10
47          1  15  19
48          1  19  11
49          1  16  18

In [10]:
w=np.zeros(x.shape[1])

In [11]:
w

array([0., 0., 0.])

In [12]:
def myprediction(features,weights):
    
    predictions=np.dot(features,weights)
    return(predictions)


In [13]:
myprediction(x,w)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)


In [15]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)

In [16]:
mycost(y,x,w)

64598.01616784157

In [17]:
def gradient(target,features,weights):
    error=myerror(target,features,weights)
    gradient = - np.dot(features.T,error)
    
    return(gradient)

In [18]:
gradient(y,x,w)

array([ 1350.38719261,  8799.15808596, 21752.03137127])

In [32]:
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(100000):
        
        weights -= learning_rate*gradient(target,features,weights)
        weights[0] -=10*learning_rate*gradient(target,features,weights)[0]
        
        if i%1000==0:
            print(mycost(target,features,weights),weights)
    return(weights)

In [33]:
my_lr(y,x,0.000001)

63464.41068391543 [-0.0146792  -0.00879916 -0.02175203]
1199.5722363413518 [-0.98337098  1.48059459 -3.26175714]
129.59025725355335 [-0.81027529  2.00549084 -3.67546985]
75.457708304633 [-0.63097542  2.11190332 -3.77019452]
67.49846571909178 [-0.45642824  2.12979039 -3.79698512]
62.07537411387313 [-0.28869846  2.12910601 -3.80908603]
57.188215402233666 [-0.12797666  2.12467435 -3.81779901]
52.7119164393799 [ 0.02593345  2.11963055 -3.82553205]
48.60863810510147 [ 0.17330012  2.11463159 -3.83280687]
44.847147158823965 [ 0.3143972   2.10980936 -3.83974474]
41.39896731436698 [ 0.4494905   2.10518468 -3.84638158]
38.23800120734457 [ 0.5788353   2.10075518 -3.85273477]
35.34032555478799 [ 0.70267617  2.09651382 -3.85881736]
32.68400976210931 [ 0.8212473   2.09245287 -3.86464106]
30.248949929084212 [ 0.93477293  2.08856471 -3.87021694]
28.0167166958263 [ 1.04346776  2.084842   -3.87555555]
25.970415763057442 [ 1.14753735  2.08127769 -3.88066699]
24.09456003030306 [ 1.24717853  2.07786506 -3.

array([ 3.42844241,  2.00315844, -3.99269492])

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
lr=LinearRegression()

In [29]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [30]:
lr.coef_

array([ 2.0010795 , -3.99567624])

In [31]:
lr.intercept_

3.4891425556807043