In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))


x2=np.random.randint(low=1,high=20,size=(50,))

In [3]:
y=3+2*x1-4*x2+np.random.random((50,))

In [4]:
y

array([-58.31707105, -46.10502978,   5.51775612, -20.68371757,
        35.91668618, -34.52817408, -66.87380797, -14.48838437,
       -10.64635386, -48.17461978, -48.74205861,  17.00191935,
       -30.96582492,  -0.68929868, -32.07753284, -60.89802455,
        21.67279645, -40.98273753, -42.65950451,  -8.26076627,
       -70.98302591, -34.51281792, -12.50382811,  25.6530583 ,
         7.66669377,   1.9713174 ,  -4.71239481, -52.43312737,
        15.79274657,  11.37732118,  23.69628489,  15.66399197,
         1.75269445,   1.01199843, -40.65261822, -32.73691329,
         5.04988469, -24.69545026,   9.01101039,   7.32096033,
       -16.38742509, -30.40212972,  -8.14835957, -48.74217874,
       -12.89528127,   1.7720283 , -28.23711413, -22.69696741,
       -14.80937796, -32.13597873])

In [5]:
x1

array([ 5,  3, 17,  4, 18, 17,  1, 15, 19,  2, 10, 17, 11,  4, 18,  6, 17,
        2,  1, 10,  1,  9,  2, 19, 14,  1, 18, 10, 12, 10, 12, 18, 17, 11,
       12, 12, 19, 16,  9, 16, 18,  7,  4,  4, 10,  7, 10,  3, 11, 12])

In [6]:
x2

array([18, 14,  8,  8,  1, 18, 18, 12, 13, 14, 18,  5, 14,  3, 18, 19,  4,
       12, 12,  8, 19, 14,  5,  4,  6,  1, 11, 19,  3,  3,  1,  6,  9,  6,
       17, 15,  9, 15,  3,  7, 14, 12,  5, 15,  9,  4, 13,  8, 10, 15])

In [9]:


x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})

w=np.zeros(x.shape[1])

In [10]:
def myprediction(features,weights):

    predictions=np.dot(features,weights)
    return(predictions)

myprediction(x,w)


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [12]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)

In [14]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)

mycost(y,x,w)


48913.862464938742

In [15]:
def gradient(target,features,weights):
    
    error=myerror(target,features,weights)
    
    gradient=-np.dot(features.T,error)
    
    return(gradient)

gradient(y,x,w)

array([   844.92874613,   4506.53131309,  15191.58686621])

In [33]:
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights)
        weights[0] -=10*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn, why?
        if i%100==0:
            print(mycost(target,features,weights),weights)
    return(weights)

my_lr(y,x,0.000001)

48398.7631201 [-0.00919208 -0.00450653 -0.01519159]
24200.9546193 [-0.52714735 -0.06748625 -1.06514331]
16077.8393744 [-0.67187312  0.18818337 -1.64143329]
11123.0685471 [-0.70903994  0.4871006  -2.03807799]
7740.82188044 [-0.71350399  0.75991839 -2.34520581]
5399.89200568 [-0.70666008  0.99363566 -2.59459799]
3777.01663928 [-0.69487359  1.18994032 -2.80061625]
2651.62111347 [-0.68024229  1.35373736 -2.9718341 ]
1871.07276385 [-0.66361709  1.49008953 -3.11444338]
1329.58427565 [-0.64545583  1.60348584 -3.2333347 ]
953.822847498 [-0.62606947  1.6977404  -3.33250594]
692.952406041 [-0.60569718  1.77605026 -3.41526506]
511.732053769 [-0.58453242  1.84108327 -3.48436047]
385.73185278 [-0.56273459  1.89506236 -3.54207891]
298.016294815 [-0.5404358   1.93983879 -3.59032385]
236.845199938 [-0.51774578  1.97695406 -3.63068002]
194.079921636 [-0.4947557   2.00769166 -3.66446684]
164.078488008 [-0.47154126  2.03312023 -3.69278285]
142.929685764 [-0.44816538  2.05412949 -3.71654271]
127.922107922

19.9630175205 [ 1.88714841  2.06948265 -3.93554625]
19.7653490903 [ 1.89737254  2.06907194 -3.93601081]
19.5701323407 [ 1.90753306  2.06866377 -3.93647247]
19.3773368634 [ 1.91763038  2.06825815 -3.93693127]
19.1869326274 [ 1.92766488  2.06785505 -3.93738721]
18.9988899743 [ 1.93763696  2.06745446 -3.93784031]
18.8131796132 [ 1.947547    2.06705636 -3.9382906 ]
18.6297726168 [ 1.9573954   2.06666074 -3.93873808]
18.4486404165 [ 1.96718253  2.06626758 -3.93918278]
18.2697547979 [ 1.97690878  2.06587686 -3.93962472]
18.0930878968 [ 1.98657452  2.06548858 -3.9400639 ]
17.9186121943 [ 1.99618013  2.06510271 -3.94050036]
17.7463005131 [ 2.00572599  2.06471924 -3.94093409]
17.5761260129 [ 2.01521246  2.06433815 -3.94136513]
17.4080621861 [ 2.02463992  2.06395944 -3.94179349]
17.2420828541 [ 2.03400873  2.06358308 -3.94221919]
17.078162163 [ 2.04331926  2.06320907 -3.94264223]
16.9162745793 [ 2.05257187  2.06283738 -3.94306264]
16.7563948865 [ 2.06176692  2.062468   -3.94348044]
16.5984981808

6.16260984433 [ 2.92888101  2.02763489 -3.98287976]
6.13610780146 [ 2.93262468  2.0274845  -3.98304986]
6.10993446329 [ 2.93634506  2.02733505 -3.9832189 ]
6.0840857529 [ 2.94004229  2.02718653 -3.98338689]
6.05855764394 [ 2.94371653  2.02703893 -3.98355384]
6.03334615999 [ 2.9473679   2.02689225 -3.98371975]
6.00844737394 [ 2.95099657  2.02674648 -3.98388463]
5.98385740741 [ 2.95460266  2.02660162 -3.98404848]
5.95957243012 [ 2.95818631  2.02645766 -3.98421131]
5.93558865928 [ 2.96174768  2.02631459 -3.98437313]
5.91190235903 [ 2.96528689  2.02617242 -3.98453394]
5.88850983984 [ 2.96880408  2.02603113 -3.98469375]
5.86540745795 [ 2.97229939  2.02589072 -3.98485257]
5.84259161478 [ 2.97577296  2.02575118 -3.9850104 ]
5.82005875641 [ 2.97922492  2.02561251 -3.98516725]
5.79780537296 [ 2.9826554   2.0254747  -3.98532312]
5.77582799812 [ 2.98606455  2.02533775 -3.98547802]
5.75412320855 [ 2.98945248  2.02520166 -3.98563196]
5.73268762337 [ 2.99281934  2.0250664  -3.98578494]
5.71151790365

4.31594259194 [ 3.30894256  2.01236732 -4.00014872]
4.31234475375 [ 3.31032193  2.01231191 -4.0002114 ]
4.30879153953 [ 3.31169271  2.01225684 -4.00027368]
4.30528239581 [ 3.31305496  2.01220212 -4.00033558]
4.30181677599 [ 3.31440874  2.01214774 -4.00039709]
4.29839414022 [ 3.3157541   2.01209369 -4.00045822]
4.2950139554 [ 3.31709109  2.01203998 -4.00051897]
4.29167569498 [ 3.31841976  2.01198661 -4.00057934]
4.288378839 [ 3.31974017  2.01193357 -4.00063934]
4.2851228739 [ 3.32105236  2.01188086 -4.00069896]
4.28190729252 [ 3.32235639  2.01182847 -4.00075821]
4.27873159399 [ 3.32365231  2.01177641 -4.00081709]
4.27559528362 [ 3.32494016  2.01172468 -4.00087561]
4.2724978729 [ 3.32622     2.01167326 -4.00093376]
4.26943887934 [ 3.32749189  2.01162217 -4.00099155]
4.26641782647 [ 3.32875586  2.0115714  -4.00104898]
4.2634342437 [ 3.33001196  2.01152094 -4.00110606]
4.2604876663 [ 3.33126026  2.01147079 -4.00116278]
4.25757763528 [ 3.33250078  2.01142096 -4.00121914]
4.25470369736 [ 3.3

4.06427375572 [ 3.44999037  2.00670125 -4.00655755]
4.06379736485 [ 3.4504923   2.00668108 -4.00658036]
4.06332688265 [ 3.4509911   2.00666105 -4.00660302]
4.06286223585 [ 3.4514868   2.00664113 -4.00662554]
4.06240335205 [ 3.45197942  2.00662134 -4.00664793]
4.06195015979 [ 3.45246897  2.00660168 -4.00667017]
4.06150258846 [ 3.45295547  2.00658213 -4.00669228]
4.06106056837 [ 3.45343895  2.00656271 -4.00671425]
4.06062403064 [ 3.45391943  2.00654341 -4.00673608]
4.06019290729 [ 3.45439691  2.00652423 -4.00675777]
4.05976713117 [ 3.45487142  2.00650517 -4.00677933]
4.05934663594 [ 3.45534298  2.00648623 -4.00680076]
4.05893135611 [ 3.45581161  2.0064674  -4.00682205]
4.058521227 [ 3.45627733  2.00644869 -4.00684321]
4.05811618471 [ 3.45674014  2.0064301  -4.00686424]
4.05771616616 [ 3.45720008  2.00641162 -4.00688514]
4.05732110904 [ 3.45765715  2.00639326 -4.00690591]
4.05693095181 [ 3.45811138  2.00637501 -4.00692655]
4.0565456337 [ 3.45856279  2.00635688 -4.00694706]
4.05616509469 [

4.03095020704 [ 3.50131517  2.00463946 -4.00888961]
4.03088712798 [ 3.50149781  2.00463213 -4.00889791]
4.03082483128 [ 3.50167932  2.00462483 -4.00890616]
4.03076330725 [ 3.50185969  2.00461759 -4.00891435]
4.03070254631 [ 3.50203895  2.00461039 -4.0089225 ]
4.03064253898 [ 3.50221709  2.00460323 -4.00893059]
4.03058327592 [ 3.50239412  2.00459612 -4.00893864]
4.0305247479 [ 3.50257005  2.00458905 -4.00894663]
4.03046694581 [ 3.50274488  2.00458203 -4.00895457]
4.03040986063 [ 3.50291863  2.00457505 -4.00896247]
4.03035348348 [ 3.5030913   2.00456811 -4.00897031]
4.03029780558 [ 3.50326289  2.00456122 -4.00897811]
4.03024281825 [ 3.50343341  2.00455437 -4.00898586]
4.03018851293 [ 3.50360288  2.00454756 -4.00899356]
4.03013488115 [ 3.50377129  2.0045408  -4.00900121]
4.03008191457 [ 3.50393865  2.00453407 -4.00900881]
4.03002960494 [ 3.50410497  2.00452739 -4.00901637]
4.0299779441 [ 3.50427026  2.00452075 -4.00902388]
4.029926924 [ 3.50443452  2.00451415 -4.00903135]
4.02987653672 [ 

4.02656351723 [ 3.51978946  2.00389733 -4.00972903]
4.02655484626 [ 3.51985718  2.00389461 -4.00973211]
4.02654628283 [ 3.51992448  2.0038919  -4.00973517]
4.02653782562 [ 3.51999135  2.00388922 -4.00973821]
4.0265294733 [ 3.52005781  2.00388655 -4.00974123]
4.02652122458 [ 3.52012386  2.00388389 -4.00974423]
4.02651307816 [ 3.52018949  2.00388126 -4.00974721]
4.02650503279 [ 3.52025472  2.00387864 -4.00975017]
4.0264970872 [ 3.52031954  2.00387603 -4.00975312]
4.02648924016 [ 3.52038396  2.00387344 -4.00975605]
4.02648149044 [ 3.52044798  2.00387087 -4.00975895]
4.02647383685 [ 3.5205116   2.00386832 -4.00976184]
4.02646627818 [ 3.52057482  2.00386578 -4.00976472]
4.02645881327 [ 3.52063765  2.00386325 -4.00976757]
4.02645144094 [ 3.52070009  2.00386074 -4.00977041]
4.02644416005 [ 3.52076214  2.00385825 -4.00977323]
4.02643696947 [ 3.52082381  2.00385577 -4.00977603]
4.02642986807 [ 3.52088509  2.00385331 -4.00977881]
4.02642285474 [ 3.52094599  2.00385087 -4.00978158]
4.02641592841 

array([ 3.5219791 ,  2.00380937, -4.00982852])

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
lr=LinearRegression()

In [25]:
x.shape

(50, 3)

In [30]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [31]:
lr.coef_

array([ 2.00346005, -4.01022363])

In [32]:
lr.intercept_

3.530674802067832